---
- name: Make sure we have the necessary deb packages available for selinux
  ansible.builtin.apt:
    name: "{{ item }}"
    update_cache: true
    state: present
  with_items:
    - python3-selinux
    - python3-semanage

